version: "3"
services:
  sandwichdb:
    image: postgres
    ports:
      - "5432:5432"
  sandwich:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: postgres
    depends_on:
      - sandwichdb
    ports:
      - "8080:8080"